name = "Sym"
uuid = "ad95715c-d4bb-11e9-1b11-ef079580f70b"
authors = ["Roger-luo"]
version = "0.1.0"

[compat]
julia = "1.1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
